"$schema" = "node_modules/wrangler/config-schema.json"
name = "jitori"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-04-13"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[vars]
PUBLIC_AUDIO_BASE_URL = "https://jitori-storage.davidmartins.net"

[[d1_databases]]
binding = "DB"
database_name = "jitori"
database_id = "ad39fecc-3901-441e-9b9b-c7e168b52d8d"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "jitori-storage"

[[routes]]
pattern = "jitori.davidmartins.net"
custom_domain = true
